### ISSUE TITLE
Option to flip camera so camera can be inverted upside on bed.

### ISSUE THREAD

**Issue by rhys100** [AstroPrint/AstroBox#287] opened 2017-06-16 05:16 UTC
Is it possible to invert the webcam image to its able to be mounted upside down

**Comment by CoDanny** [comment] 2017-06-16 09:51
Not at the moment but it's already logged as an issue.

**Comment by CoDanny** [comment] 2017-06-16 09:51
duplicate of #75

**Closed by CoDanny** 2017-06-16 09:51 UTC

**Comment by Cyphen-Cyn** [comment] 2017-08-13 00:31
Where is the option to flip camera?

**Comment by CoDanny** [comment] 2017-08-13 19:35
@Cyphen-Cyn It's not implemented yet. This was closed because the same request already exists on #75
