### ISSUE TITLE
GCODE terminal should default to all caps.

### ISSUE THREAD

**Issue by acunyc** [AstroPrint/AstroBox#80] opened 2016-01-17 04:02 UTC
Quote from a printer manufacturer that we work with:

"The terminal on astroprint doesn't auto-uppercase text.  This can cause the printer to hang up when sending lowercase code accidentally!  Can you guys fix it so that it automatically uppercases anything entered in the gcode terminal window?  I patched it on my end to do this, but this should be done always, but in the event someone for some reason DOESNT need it, myabe a check box that is auto selected that uppercases?"

**Comment by CoDanny** [comment] 2016-01-17 11:11
duplicate of #76

**Closed by CoDanny** 2016-01-17 11:11 UTC
